language: ruby
dist: xenial
cache: bundler

addons:
  apt:
    packages:
      - libvips

matrix:
  include:
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.6
      env: COVERAGE=BriefSummary,Coveralls
    - rvm: jruby-head
    - rvm: truffleruby
    - rvm: ruby-head
  allow_failures:
    - rvm: jruby-head
    - rvm: truffleruby
    - rvm: ruby-head
